 create table if not exists users(
     id int generated by default as identity primary key ,
     first_name varchar(30) not null ,
     last_name varchar(30) not null ,
     email varchar(50) not null unique ,
     password varchar not null
 )