 create table if not exists users (
     id bigint generated by default as identity primary key ,
     first_name varchar(30) not null ,
     last_name varchar(30) not null ,
     email varchar(50) not null unique ,
     password varchar not null,
     role varchar(20) not null
 );

 create table if not exists refresh_token (
     id int generated by default as identity primary key,
     user_id int references users (id) on delete cascade ,
     token varchar not null,
     expiry_date timestamp not null
 )